on:
  [push, pull_request]
jobs:
  notif-script:
    runs-on: ubuntu-latest
    name: workflow that pushes repo news to xmpp server
    steps:
      - name: push_info_step
        id: push
        uses: processone/xmpp-notifier@remove-checkout-fixed
        # Will only trigger when a push is made to the master branch
        if: github.event_name == 'push'
        with: # Set the secrets as inputs
          # Login expects the bot's bare jid (user@domain)
          jid: ${{ secrets.bot_username }}
          password: ${{ secrets.bot_password }}
          server_host: ${{ secrets.server_rooms_domain }}
          recipient: ${{ secrets.room }}
          # Port is optional. Defaults to 5222
          server_port: ${{ secrets.server_port }}
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }} with message:
            ${{ join(github.event.commits.*.message) }}
          # Boolean to indicate if correspondent should be treated as a room (true) or a single user
          recipient_is_room: true
      - name: pr_open_info_step
        id: pull_request_open
        uses: processone/xmpp-notifier@remove-checkout-fixed
        # Will only get triggered when a pull request to master is created
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with: # Set the secrets as inputs
          jid: ${{ secrets.bot_username }}
          password: ${{ secrets.bot_password }}
          server_host: ${{ secrets.server_rooms_domain }}
          recipient: ${{ secrets.room }}
          message: |
            ${{ github.actor }} opened a PR : ${{ github.event.pull_request.html_url }} with message :
            ${{ github.event.pull_request.title }}
          recipient_is_room: true
      - name: pr_edit_info_step
        id: pull_request_edit
        uses: processone/xmpp-notifier@remove-checkout-fixed
        # Will only get triggered when a pull request to master is created
        if: github.event_name == 'pull_request' && github.event.action == 'edited'
        with: # Set the secrets as inputs
          jid: ${{ secrets.bot_username }}
          password: ${{ secrets.bot_password }}
          server_host: ${{ secrets.server_rooms_domain }}
          recipient: ${{ secrets.room }}
          message: |
            ${{ github.actor }} edited the following PR : ${{ github.event.pull_request.html_url }} with message :
            ${{ github.event.pull_request.title }}
          recipient_is_room: true